const Movie = require('../models/Movie');
const Admin = require('../models/Admin');
const bcrypt = require('bcrypt');

const sendMail = require('../utils/nodeMailer');
// Render the Add Movie Page
exports.addMoviePage = (req, res) => {
    res.render('addmovie');
};

// Process the Form Submission
// exports.addMovie = async (req, res) => {
//     try {
//         const { title, genre, duration, rating } = req.body;

//         const newMovie = new Movie({
//             title,
//             genre,
//             duration,
//             rating,
//             poster: req.file.filename // The filename generated by Multer
//         });

//         await newMovie.save();
//         res.redirect('/'); // Go back to home to see the new movie card
//     } catch (error) {
//         console.error("Error adding movie:", error);
//         res.status(500).send("Server Error: Could not save movie.");
//     }
// };


exports.addMoviePage = (req, res) => {
    res.render('admin/addmovie'); // Looks for views/admin/addmovie.ejs
};

exports.addMovie = async (req, res) => {
    try {
        const { title, genre, rating, poster, duration, description } = req.body;

        await Movie.create({
            title,
            genre,
            rating,
            poster, // This will now save the URL string directly
            duration,
            description
        });

        res.redirect('/');
    } catch (err) {
        console.error(err);
        res.status(500).send("Error adding movie");
    }
};


exports.registrationPage = (req, res) => {
    res.render('registration')
}

exports.registerUser = async (req, res) => {
    const password = req.body.password;
    const conf_password = req.body.conf_password;
    const username = req.body.username;
    const email = req.body.email;
    if (password != conf_password) {
        return res.redirect('/registration')
    }

    const hashedPassword = await bcrypt.hash(password, 10);

    const user = {
        username: username,
        email: email,
        password: hashedPassword
    }
    await Admin.create(user);
    res.redirect('/login')
}


exports.loginPage = (req, res) => {
    res.render('login');
}

exports.loginUser = async (req, res) => {
    const { username, password } = req.body;
    try {
        const user = await Admin.findOne({ username });
        if (user && await bcrypt.compare(password, user.password)) {
            res.cookie('userID', user._id);
            console.log("Login successful");
            console.log("sending email");

            sendMail(user.email, user.username);
            res.redirect('/');

        } else {
            res.redirect('/login');
        }
    } catch (err) {
        console.error(err);
        res.status(500).send("Error during login");
    }
}


exports.adminPage = async (req, res) => {
    try {
        const movies = await Movie.find();
        res.render('adminIndex', { movies });
    } catch (err) {
        console.error(err);
        res.status(500).send("Error fetching movies");
    }
}



